INSERT INTO `language` (`id`, `name`, `localized`) VALUE ('de', 'German', 'Deutsch');

INSERT INTO translation (`key`, language_id, value)
VALUES ('embed.footer.developer', 'de', 'Entwickelt von Akio Nakao#0001'),
       ('embed.footer.pagination', 'de', 'Seite %1$s/%2$s'),
       ('embed.footer.xodb', 'de', 'Unterstützt von CrossoutDB'),
       ('embed.header.full', 'de', '**%1$s**\n[Auf CrossoutDB anschauen](%2$s) • [Einen Fehler melden](%3$s)'),
       ('embed.header.simple', 'de', '**%1$s**\n[Einen Fehler melden](%2$s)'),
       ('embed.invite', 'de', 'Hier Clicken um den Bot einzuladen'),
       ('general.forbidden', 'de', 'Es ist dir nicht erlaubt dies zu tun.'),
       ('general.xodb.error', 'de',
        'Ein Fehler trat auf beim abrufen der Daten von CrossoutDB. Bitte versuche es später noch einmal.'),
       ('general.xodb.offline', 'de',
        'CrossoutDB scheint nicht erreichbar zu sein. Bitte versuche es später noch einmal.'),
       ('item.removed', 'de', '> *Dieser Gegenstand wurde entfernt*'),
       ('language.unsupported', 'de', 'Diese Sprache ist (noch?) nicht unterstützt.'),
       ('language.updated.channel', 'de', 'Die Kanalsprache wurde geändert.'),
       ('language.updated.guild', 'de', 'Die Serversprache wurde geändert.'),
       ('language.updated.user', 'de', 'Deine Sprache wurde geändert.'),
       ('market.buy', 'de', 'Markt Kauf'),
       ('market.buyOrders', 'de', 'Kaufanfragen'),
       ('market.craft.buy', 'de', 'Markt Kauf Herstellung'),
       ('market.craft.sell', 'de', 'Markt Verkauf Herstellung'),
       ('market.currency', 'de', 'Coins'),
       ('market.price', 'de', '%,.2f %s (%s)'),
       ('market.sell', 'de', 'Markt Verkauf'),
       ('market.sellOffers', 'de', 'Verkaufsangebote'),
       ('market.simplePrice', 'de', '%.2f %s'),
       ('pack.price', 'de', 'Paketpreise'),
       ('search.empty', 'de', 'Die Suche ergab keine Treffer'),
       ('search.results', 'de', 'Suchergebnisse'),
       ('trigger.buy.over', 'de', '%1$s wenn Markt Kaufpreis über %2$s ist, alle %3$s'),
       ('trigger.buy.under', 'de', '%1$s wenn Markt Kaufpreis unter %2$s ist, alle %3$s'),
       ('trigger.everytime', 'de', '%1$s alle %2$s'),
       ('trigger.sell.over', 'de', '%1$s wenn Markt Verkaufspreis über %2$s ist, alle %3$s'),
       ('trigger.sell.under', 'de', '%1$s wenn Markt Verkaufspreis unter %2$s ist, alle %3$s'),
       ('watcher.already.paused', 'de', 'Deine Beobachter sind bereits pausiert'),
       ('watcher.already.resumed', 'de', 'Deine Beobachter sind bereits fortgesetzt'),
       ('watcher.created', 'de', 'Der Beobachter mit der ID %1$s wurde erstellt'),
       ('watcher.deleted', 'de', 'Der Beobachter wurde entfernt'),
       ('watcher.empty', 'de', 'Du hast (noch) keine Beobachter'),
       ('watcher.item.none', 'de', 'Beobachter konnte nicht erstellt werden: Gegenstand nicht gefunden'),
       ('watcher.item.tooMany', 'de', 'Beobachter konnte nicht erstellt werden: Zu viele Gegenstände'),
       ('watcher.notFound', 'de', 'Beobachter nicht gefunden'),
       ('watcher.ownership', 'de', 'Du bist nicht der Eigentümer dieses Beobachters'),
       ('watcher.params.frequency', 'de', 'Bitte eine Frequenz von mindestens 5m angeben'),
       ('watcher.params.name', 'de', 'Der Beobachtername sollte nicht mehr als 255 Zeichen enthalten'),
       ('watcher.params.price', 'de', 'Bitte einen gültigen Preis angeben'),
       ('watcher.params.priceTrigger', 'de', 'Bitte einen Preis für den ausgewählten Auslöser angeben'),
       ('watcher.status.paused', 'de', 'Deine Beobachter wurden pausiert'),
       ('watcher.status.resumed', 'de', 'Deine Beobachter wurden fortgesetzt'),
       ('watcher.updated', 'de', 'Der Beobachter wurde geändert');

