name: Java CI

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            -   name: echo ref
                run: echo ${{ github.ref }}
            -   uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'adopt'
            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1.0.4
            -   name: Change gradlew to executable
                run: chmod +x gradlew
            -   name: Build with Gradle
                run: ./gradlew build
            -   name: Create Release
                uses: softprops/action-gh-release@v0.1.13
                with:
                    files: build/libs/*.jar
                    token: ${{ secrets.GITHUB_TOKEN }}
